<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Andrew Callan" />
    <meta name="description" content="Describe your website">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Crohn&#39;s Disease</title>
    <meta name="generator" content="Hugo 0.70.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/resume.pdf">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project2/">Crohn&#39;s Disease</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          April 30, 2020
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="an-analysis-by-andrew-callan" class="section level2">
<h2>An analysis by Andrew Callan</h2>
<pre class="r"><code>CrohnD &lt;- read.csv(&quot;https://vincentarelbundock.github.io/Rdatasets/csv/robustbase/CrohnD.csv&quot;)
head(CrohnD)</code></pre>
<pre><code>## X ID nrAdvE BMI height country sex age weight treat
## 1 1 19908 4 25.22 163 c1 F 47 67 placebo
## 2 2 19909 4 23.80 164 c1 F 53 64 d1
## 3 3 19910 1 23.05 164 c1 F 68 62 placebo
## 4 4 20908 1 25.71 165 c1 F 48 70 d2
## 5 5 20909 2 25.95 170 c1 F 67 75 placebo
## 6 6 20910 2 28.70 168 c1 F 54 81 d1</code></pre>
<pre class="r"><code>?CrohnD</code></pre>
<pre><code>## No documentation for &#39;CrohnD&#39; in specified packages and
libraries:
## you could try &#39;??CrohnD&#39;</code></pre>
<p>This dataset is the results from a study on 117 Crohn’s disease patients and the adverse effects they experienced while taking a drug for their Crohn’s disease. The ‘ID’ column is a numeric variable that identifies each unique patient. The ‘nrAdvE’ variable is a numeric variable that counts the number of adverse events the patient reported experiencing. ‘BMI’ is the recorded BMI of each patient ([kg]/[m^2]). The ‘height’ column is each patient’s recorded height in centimeters. All patients were from one of two countries, so the binary variable ‘Country’ separates the patients into either 0 or 1. ‘Sex’ is a binary factor separating patients into the categories Male or Female. The ‘age’ column is a numeric variable describing the patient’s age in years. The ‘weight’ varibable is the patient’s weight in kilograms. Finally, the ’treat; variable is a categorical variable describing whether the patient was taking the placebo drug, drug dose 1, or drug dose 2.</p>
</div>
<div id="manova" class="section level1">
<h1>MANOVA</h1>
<pre class="r"><code>man1&lt;-manova(cbind(nrAdvE, weight, BMI, height)~treat, data=CrohnD)
summary(man1)</code></pre>
<pre><code>##            Df  Pillai approx F num Df den Df Pr(&gt;F)
## treat       2 0.10389   1.5341      8    224 0.1465
## Residuals 114</code></pre>
<pre class="r"><code>1-(0.95^1) #5% chance of a type 1 error</code></pre>
<pre><code>## [1] 0.05</code></pre>
<pre class="r"><code>0.05/1 #0.05 is the Bonferroni correction</code></pre>
<pre><code>## [1] 0.05</code></pre>
<p>The variables nrAdvE, weight, BMI, and height were all numerical variables that were tested to see if there was a mean difference between the three different treatment groups. The MANOVA showed no significance between the treatment groups for any of the numeric variables tested. Since there was no significance found, I did not perform univariate ANOVAs or post-hoc t-tests. Therefore, the alpha value is not adjusted and will remain at 0.05. There is 5% change of a type 1 error.
As for assumptions, because this data is patient data, it is likely not a random sample of people. I can assume that the observations are indpendent of each other. MANOVA assumes that the response variables show multivariate normality, which is a difficult assumption to make. MANOVA also assumes that there is homogeneity of within-group covariance matrices, which is also a high barrier. Because these are very difficult to reach and the results did not yield any significance, it is saf to assume these assumptions were not met. MANOVA assumes no extreme univariate or covariate outliers, which is likely not met. Finally, MANOVA assumes no multicolinearity. This is likely broken, since variables like “weigh”, “height”, and “BMI” are dependent on each other. Therefore, we would see the variables be highly correlated.</p>
</div>
<div id="permanova" class="section level1">
<h1>PERMANOVA</h1>
<pre class="r"><code>library(vegan)
dists&lt;-CrohnD%&gt;%select(nrAdvE, BMI, height, weight)%&gt;%dist()
adonis(dists~treat,data=CrohnD)</code></pre>
<pre><code>## 
## Call:
## adonis(formula = dists ~ treat, data = CrohnD) 
## 
## Permutation: free
## Number of permutations: 999
## 
## Terms added sequentially (first to last)
## 
##            Df SumsOfSqs MeanSqs F.Model      R2 Pr(&gt;F)
## treat       2       726  362.76  1.1645 0.02002  0.316
## Residuals 114     35512  311.51         0.97998       
## Total     116     36238                 1.00000</code></pre>
<pre class="r"><code>#compute observed F
SST&lt;- sum(dists^2)/117
SSW&lt;-CrohnD%&gt;%group_by(treat)%&gt;%select(nrAdvE, BMI, height, weight)%&gt;%
do(d=dist(.[2:3],&quot;euclidean&quot;))%&gt;%ungroup()%&gt;%
summarize(sum(d[[1]]^2)/50 + sum(d[[2]]^2)/50+ sum(d[[3]]^2)/50)%&gt;%pull
F_obs&lt;-((SST-SSW)/2)/(SSW/114)

Fs&lt;-replicate(1000,{
new&lt;-CrohnD%&gt;%mutate(treat=sample(treat))
SSW&lt;-new%&gt;%group_by(treat)%&gt;%select(nrAdvE, BMI, height, weight)%&gt;%
do(d=dist(.[2:3],&quot;euclidean&quot;))%&gt;%ungroup()%&gt;%
summarize(sum(d[[1]]^2)/50 + sum(d[[2]]^2)/50+ sum(d[[3]]^2)/50)%&gt;%pull
((SST-SSW)/2)/(SSW/114)
})

{hist(Fs,prob = T); abline(v=F_obs, col=&quot;red&quot;, add=T)}</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mean(Fs&gt;F_obs)</code></pre>
<pre><code>## [1] 0.417</code></pre>
<p>Null Hypothesis: The center and spread of all three treament groups were the same.
Alternate Hypothesis: At least one of the group’s center or spead was different than the others.
The p-vaule is greater than 0.05, meaning that the three treatment groups do not have significantly different centers or spreads.</p>
</div>
<div id="linear-regression" class="section level1">
<h1>Linear Regression</h1>
<pre class="r"><code>CrohnD$nrAdvE_c=CrohnD$nrAdvE-mean(CrohnD$nrAdvE)
CrohnD$height_c=CrohnD$height-mean(CrohnD$height)
CrohnD$weight_c=CrohnD$weight-mean(CrohnD$weight)
CrohnD$BMI_c=CrohnD$BMI-mean(CrohnD$BMI)
CrohnD &lt;- CrohnD %&gt;% mutate(treat=as.factor(treat))
fit &lt;-lm(nrAdvE ~ treat*BMI_c, data=CrohnD)
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = nrAdvE ~ treat * BMI_c, data = CrohnD)
##
## Residuals:
## Min 1Q Median 3Q Max
## -4.1234 -1.7348 -0.9288 0.8387 10.0052
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 1.61633 0.42725 3.783 0.000251 ***
## treatd2 0.52934 0.60800 0.871 0.385833
## treatplacebo 0.91887 0.60787 1.512 0.133469
## BMI_c 0.17096 0.07350 2.326 0.021831 *
## treatd2:BMI_c -0.19097 0.10990 -1.738 0.085036 .
## treatplacebo:BMI_c 0.04939 0.14393 0.343 0.732122
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 2.664 on 111 degrees of freedom
## Multiple R-squared: 0.08777, Adjusted R-squared: 0.04668
## F-statistic: 2.136 on 5 and 111 DF, p-value: 0.06632</code></pre>
<pre class="r"><code>coef(fit)</code></pre>
<pre><code>## (Intercept) treatd2 treatplacebo BMI_c treatd2:BMI_c
## 1.61632542 0.52934311 0.91887287 0.17095900 -0.19097485
## treatplacebo:BMI_c
## 0.04939374</code></pre>
<p>Predicted number of adverse side effects for someone with an average BMI in the placebo treatment group is 2.53520 events. Patients with an average BMI in the d1 treatment group had on average 0.91887 fewer adverse side effect events than patients in the placebo treatment group. For patients with an average BMI in the d2 treatment group, there was an average of 0.38953 fewer adverse side effect events than patients in the placebo treatment group. As BMI increases by 1 for patients in the placebo treatment group, the number of adverse side effect events increases on average by 0.22035. The slope for BMI on the number of adverse side effect events is 0.04939 lower for the d1 treatment group than the placebo treatment group. The slope for BMI on number of adverse side effect events is 0.24037 lower for the d2 treatment group than the placebo treatment group.</p>
<pre class="r"><code>CrohnD %&gt;% ggplot(aes(BMI_c, nrAdvE , color = treat)) + 
geom_point() + geom_smooth(method = &#39;lm&#39;, se = F, fullrange = T) + 
ggtitle(&quot;Linear Regression Predicting Number of Adverse Side Effect 
Events with BMI and Treatment Group&quot;) + 
  ylab(&quot;Number of Adverse Side Effect Events&quot;) + xlab(&quot;BMI&quot;) + 
  labs(color = &quot;Treament Group&quot;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#Testing Normality
resids&lt;-lm(nrAdvE ~ treat*BMI_c, data=CrohnD)$residuals
shapiro.test(resids) #reject null, there is no normality</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resids
## W = 0.87767, p-value = 2.267e-08</code></pre>
<pre class="r"><code>#Testing Homoskedasticity
library(sandwich)
library(lmtest)
bptest(fit) # fail to reject null, homoskedastic</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit
## BP = 8.6397, df = 5, p-value = 0.1243</code></pre>
<pre class="r"><code>#Testing Linerity
CrohnD %&gt;% filter(treat == &quot;placebo&quot;) %&gt;% ggplot(aes(BMI_c, nrAdvE)) + geom_point()</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-7-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>CrohnD %&gt;% filter(treat == &quot;d1&quot;) %&gt;% ggplot(aes(BMI_c, nrAdvE)) + geom_point()</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-7-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>CrohnD %&gt;% filter(treat == &quot;d2&quot;) %&gt;% ggplot(aes(BMI_c, nrAdvE)) + geom_point()</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-7-3.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#No clear linearity

#Test with Robust Standard Errors
coeftest(fit, vcov=vcovHC(fit))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 1.616325 0.388917 4.1560 6.395e-05 ***
## treatd2 0.529343 0.597923 0.8853 0.3779
## treatplacebo 0.918873 0.684279 1.3428 0.1821
## BMI_c 0.170959 0.114751 1.4898 0.1391
## treatd2:BMI_c -0.190975 0.147773 -1.2924 0.1989
## treatplacebo:BMI_c 0.049394 0.202067 0.2444 0.8073
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p>Using robust standard errors, no variable showed significance, unlike when the linear regression was initially run and BMI_c did show singificance. No estimates changed between the two tests.
According to the initial linear regression results, adjusted for the number of variables used, this model accounts for 4.67% of variation in the number of adverse side effect events.</p>
</div>
<div id="bootstrapped-standard-errors" class="section level1">
<h1>Bootstrapped Standard Errors</h1>
<pre class="r"><code>boot_dat&lt;- sample_frac(CrohnD, replace=T)

samp_distn&lt;-replicate(5000, {
boot_dat &lt;- sample_frac(CrohnD, replace=T) 
fit &lt;- lm(nrAdvE~BMI_c*treat, data=boot_dat)
coef(fit)
})
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = nrAdvE ~ treat * BMI_c, data = CrohnD)
##
## Residuals:
## Min 1Q Median 3Q Max
## -4.1234 -1.7348 -0.9288 0.8387 10.0052
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 1.61633 0.42725 3.783 0.000251 ***
## treatd2 0.52934 0.60800 0.871 0.385833
## treatplacebo 0.91887 0.60787 1.512 0.133469
## BMI_c 0.17096 0.07350 2.326 0.021831 *
## treatd2:BMI_c -0.19097 0.10990 -1.738 0.085036 .
## treatplacebo:BMI_c 0.04939 0.14393 0.343 0.732122
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 2.664 on 111 degrees of freedom
## Multiple R-squared: 0.08777, Adjusted R-squared: 0.04668
## F-statistic: 2.136 on 5 and 111 DF, p-value: 0.06632</code></pre>
<pre class="r"><code>samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>## (Intercept) BMI_c treatd2 treatplacebo BMI_c:treatd2
BMI_c:treatplacebo
## 1 0.3475047 0.09269006 0.5589608 0.6428684 0.1260579
0.184962</code></pre>
<p>The bootstraped standard errors are very similar to the robust stardard errors and the original standard errors. Most values are only smaller by about 0.02, which we would expect to not affect the resulting p-value by much at all. I do not believe that these bootstrapped standard errors will make any variables significant.</p>
</div>
<div id="logistic-regression" class="section level1">
<h1>Logistic Regression</h1>
<pre class="r"><code>CrohnD_new &lt;- CrohnD %&gt;% mutate(treat_b=ifelse(treat==&quot;placebo&quot;,0,1)) %&gt;% select(-ID)
fit1&lt;-glm(treat_b~BMI_c+nrAdvE,data=CrohnD_new,family=binomial(link=&quot;logit&quot;))
coeftest(fit1)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) 0.891253 0.255083 3.4940 0.0004759 ***
## BMI_c 0.046429 0.042665 1.0882 0.2764980
## nrAdvE -0.090357 0.072460 -1.2470 0.2124039
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit1))</code></pre>
<pre><code>## (Intercept)       BMI_c      nrAdvE 
##   2.4381825   1.0475237   0.9136054</code></pre>
<pre class="r"><code>predicted &lt;- predict(fit1, type = &quot;response&quot;)
pred&lt;-ifelse(predicted&gt;.5,1,0)
table(prediction=pred, truth=CrohnD_new$treat_b)%&gt;%addmargins</code></pre>
<pre><code>##           truth
## prediction   0   1 Sum
##        0     2   2   4
##        1    37  76 113
##        Sum  39  78 117</code></pre>
<pre class="r"><code>#Accuracy
(2+76)/117</code></pre>
<pre><code>## [1] 0.6666667</code></pre>
<pre class="r"><code>#TPR
76/78</code></pre>
<pre><code>## [1] 0.974359</code></pre>
<pre class="r"><code>#TNR
2/39</code></pre>
<pre><code>## [1] 0.05128205</code></pre>
<pre class="r"><code>#PPV
76/113</code></pre>
<pre><code>## [1] 0.6725664</code></pre>
<p>For every increase in BMI of 1, the odds of the patient being from either drug group increases by 1.0475237. For every increase in the number of adverse side effect events of 1, the odds of the patient being from either drug group increases by 0.9136054.
This model has an accuracy of 66.67%, meaning it correctly classified 66.67% of cases. This model has a TPR of 97.44%, meaning 97.44% of drug patients were correctly classified. The TNR of this model is 5.13%, meaning 5.13% of placebo patients were classified correctly. This model shows a PPV of 67.26%, signifying that 67.26% of patients classified as from a drug group by the model actually were from a drug group.</p>
<pre class="r"><code>CrohnD_new$logit &lt;- predict(fit1, data = CrohnD_new, type = &quot;link&quot;)
CrohnD_new$treat_b&lt;-factor(CrohnD_new$treat_b,levels=c(&quot;1&quot;,&quot;0&quot;))
CrohnD_new &lt;- CrohnD_new %&gt;% mutate(treatment=ifelse(treat==&quot;placebo&quot;,&quot;placebo&quot;,&quot;drug&quot;))
ggplot(CrohnD_new,aes(logit,fill=treatment))+geom_density(alpha=.3)+
  geom_vline(xintercept=0,lty=2) + ggtitle(&quot;Density of log-odds by Treatment Group&quot;)</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-10-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(plotROC)
CrohnD_new &lt;- CrohnD_new %&gt;% mutate(treat_b=ifelse(treat==&#39;placebo&#39;,0,1))
CrohnD_new$prob&lt;-predict(fit1,type=&quot;response&quot;)
ROCplot &lt;- ggplot(CrohnD_new)+geom_roc(aes(d=treat_b,m=prob), n.cuts=0)
ROCplot</code></pre>
<p><img src="/project2_files/figure-html/unnamed-chunk-11-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.6015779</code></pre>
<p>This ROC plote shows an AUC of 0.6015779, which means this model is poor at predicting the treatment group of a patient.</p>
<pre class="r"><code>CrohnD &lt;- CrohnD_new %&gt;% mutate(y=ifelse(treat_b==&quot;0&quot;,0,1))
fit &lt;- glm(y~nrAdvE+BMI_c,data=CrohnD,family=&quot;binomial&quot;)
prob &lt;- predict(fit,type=&quot;response&quot;)



class_diag&lt;-function(probs,truth){
if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
prediction&lt;-ifelse(probs&gt;.5,1,0)
acc=mean(truth==prediction)
sens=mean(prediction[truth==1]==1)
spec=mean(prediction[truth==0]==0)
ppv=mean(truth[prediction==1]==1)

ord&lt;-order(probs, decreasing=TRUE)
probs &lt;- probs[ord]; truth &lt;- truth[ord]
TPR=cumsum(truth)/max(1,sum(truth))
FPR=cumsum(!truth)/max(1,sum(!truth))
dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
n &lt;- length(TPR)
auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
data.frame(acc,sens,spec,ppv,auc)
}



set.seed(1234)
k=10 
data&lt;-CrohnD[sample(nrow(CrohnD)),] 
folds&lt;-cut(seq(1:nrow(CrohnD)),breaks=k,labels=F) 
diags&lt;-NULL
for(i in 1:k){

train&lt;-data[folds!=i,]
test&lt;-data[folds==i,]
truth&lt;-test$y

fit&lt;-glm(y~nrAdvE+BMI_c,data=train,family=&quot;binomial&quot;)

probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)

diags&lt;-rbind(diags,class_diag(probs,truth))
}
summarize_all(diags,mean) </code></pre>
<pre><code>##         acc      sens       spec       ppv       auc
## 1 0.6401515 0.9513889 0.03333333 0.6604545 0.5624074</code></pre>
<p>This 10-fold Cross Validation demonstrated 63.11% accuracy, 94.31% sensitivity (recall), a 2% specificity. This model has AUC of 0.5781911, making is a very poor predictor of treatment group.</p>
</div>
<div id="lasso-regression" class="section level1">
<h1>LASSO Regression</h1>
<pre class="r"><code>library(glmnet)
CrohnD2 &lt;- CrohnD %&gt;% select(1:8,treat_b,-treat)
y&lt;-as.matrix(CrohnD2$treat_b) 
x&lt;-model.matrix(treat_b~-1+.,data=CrohnD2) 
head(x)</code></pre>
<pre><code>## X nrAdvE BMI height countryc1 countryc2 sexM age weight
## 1 1 4 25.22 163 1 0 0 47 67
## 2 2 4 23.80 164 1 0 0 53 64
## 3 3 1 23.05 164 1 0 0 68 62
## 4 4 1 25.71 165 1 0 0 48 70
## 5 5 2 25.95 170 1 0 0 67 75
## 6 6 2 28.70 168 1 0 0 54 81</code></pre>
<pre class="r"><code>cv&lt;-cv.glmnet(x,y, family = &#39;binomial&#39;)
lasso&lt;-glmnet(x,y,family = &#39;binomial&#39;, lambda=cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 10 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                    s0
## (Intercept) 0.6931472
## X           0.0000000
## nrAdvE      .        
## BMI         .        
## height      .        
## countryc1   .        
## countryc2   .        
## sexM        .        
## age         .        
## weight      .</code></pre>
<p>The only variable that seems to help predict the outcome of this variable is the number of adverse side effect events, and even that was extremely small. This will be the only variable retained.</p>
<pre class="r"><code>set.seed(1234)
k=10 

data1&lt;-CrohnD2[sample(nrow(CrohnD2)),] 
folds&lt;-cut(seq(1:nrow(CrohnD2)),breaks=k,labels=F) 
diags&lt;-NULL
for(i in 1:k){

train&lt;-data1[folds!=i,]
test&lt;-data1[folds==i,]
truth&lt;-test$treat_b

fit&lt;-glm(treat_b~nrAdvE,data=train,family=&quot;binomial&quot;)
probs&lt;-predict(fit,newdata = test,type=&quot;response&quot;)

diags&lt;-rbind(diags,class_diag(probs,truth))
}
diags%&gt;%summarize_all(mean)</code></pre>
<pre><code>##         acc  sens       spec      ppv       auc
## 1 0.6568182 0.975 0.03333333 0.665303 0.5339815</code></pre>
<p>The AUC for this out-of-sample model is 0.5775397, which is slightly worse than the original model’s accuracy of 0.5781911. Given that the too models show very similar AUCs, I can assume the original model was not overfitted.</p>
</div>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
